import type { SingleQ } from '@/types/quiz-bank';

// A labelled line in a worked example, revealed step by step
export interface LessonExampleStep {
  label?: string;
  line?: string;
  action?: string;
  explanation?: string;
  math?: string;
  why?: string;
}

export interface Subject {
  id: string;
  name: string;
  slug: string;
  icon_name: string;
  icon_image_url: string | null;
  color_scheme: string;
  icon_color?: string;
  text_color?: string;
  font_size?: number;
  font_family?: string;
  lesson_text_color?: string;
  lesson_font_size?: number;
  lesson_font_family?: string;
  practice_text_color?: string;
  practice_font_size?: number;
  practice_font_family?: string;
  display_context?: 'learn' | 'practice' | 'both';
  order_index: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  // Computed fields
  total_videos?: number;
  completed_videos?: number;
  earned_xp?: number;
}

export interface Category {
  id: string;
  subject_id: string;
  name: string;
  slug: string;
  icon_name: string;
  description: string | null;
  order_index: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  // Related data
  topics?: Topic[];
}

export interface LessonExample {
  context: string;
  fraction?: string;
  total: number;
  taken: number;
  explanation: string;
}

export interface LessonVocabItem {
  term: string;
  definition: string;
}

// A single difficulty step within a progressive lesson
export interface LessonStep {
  step_name: string;
  difficulty_level: number;
  vocabulary?: LessonVocabItem[];
  explanation: string;
  example: string;
  examples?: LessonExample[];
  example_steps?: LessonExampleStep[];
  common_mistakes: (string | { mistake: string; why: string })[];
  quiz?: SingleQ;
  generated_at?: string;
}

// Lesson content structure generated by AI
export interface LessonContent {
  vocabulary?: LessonVocabItem[];
  explanation: string;
  examples?: LessonExample[];
  example: string;
  example_steps?: LessonExampleStep[];
  common_mistakes: (string | { mistake: string; why: string })[];
  quiz?: SingleQ;
  guided_practice: string[]; // Array of task IDs
  exit_ticket: string[];     // Array of task IDs
  generated_at: string;
  generated_by_model?: string;
  curriculum_level?: string;
  curriculum_country?: string;
  generated_language?: string;
  difficulty_level?: number;
  step_name?: string | null;
  // When generated in progressive mode, all steps live here
  steps?: LessonStep[];
}

export interface Topic {
  id: string;
  category_id: string;
  name: string;
  slug: string;
  description: string | null;
  video_count: number;
  quiz_count: number;
  estimated_duration_minutes: number;
  order_index: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  // Keywords for AI matching
  keywords?: string[];
  // User progress
  completed_videos?: number;
  progress_percentage?: number;
  // Curriculum location fields
  curriculum_country_code?: string | null;
  curriculum_level_code?: string | null;
  curriculum_subject_id?: string | null;
  curriculum_domain_id?: string | null;
  curriculum_subdomain_id?: string | null;
  // Linked objectives (when joined)
  topic_objective_links?: import('@/types/curriculum').TopicObjectiveWithDetails[];
  // Generated lesson content
  lesson_content?: LessonContent | null;
}

export interface Video {
  id: string;
  topic_id: string;
  subject_id?: string | null;
  title: string;
  video_url: string;
  thumbnail_url: string | null;
  duration_minutes: number;
  xp_reward: number;
  description: string | null;
  transcript: string | null;
  order_index: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  // Age and level filtering
  min_age?: number | null;
  max_age?: number | null;
  school_levels?: string[] | null;
  // Tags for homework matching
  tags?: string[] | null;
  // Language
  language?: string;
  // Multi-language variant group
  variant_group_id?: string | null;
  // User progress
  progress_percentage?: number;
  last_watched_position_seconds?: number;
  progress_type?: string;
  is_completed?: boolean;
}

export interface Quiz {
  id: string;
  video_id: string;
  question: string;
  question_latex: string | null;
  options: string[];
  correct_answer_index: number;
  explanation: string;
  timestamp_seconds: number;
  xp_reward: number;
  order_index: number;
  created_at: string;
  updated_at: string;
  // Age and level filtering
  min_age?: number | null;
  max_age?: number | null;
  school_levels?: string[] | null;
  // Language
  language?: string;
}

export interface UserProgress {
  id: string;
  user_id: string;
  subject_id: string | null;
  category_id: string | null;
  topic_id: string | null;
  video_id: string | null;
  progress_type: 'video_started' | 'video_completed' | 'quiz_attempted' | 'quiz_passed' | 'lesson_completed';
  progress_percentage: number;
  quiz_score: number | null;
  time_spent_seconds: number;
  last_watched_position_seconds: number;
  created_at: string;
  updated_at: string;
}

export interface SubjectProgress {
  subject: Subject;
  videos_ready: number;
  videos_completed: number;
  lessons_completed: number;
  progress_percentage: number;
}

// Multi-language video variant types
export interface VideoVariant {
  id?: string;
  language: string;
  video_url: string;
  title: string;
  description: string | null;
  tags: string[];
  thumbnail_url: string | null;
  transcript: string | null;
}

export interface VideoVariantGroup {
  variant_group_id: string;
  topic_id: string;
  subject_id: string | null;
  duration_minutes: number;
  xp_reward: number;
  order_index: number;
  is_active: boolean;
  min_age: number | null;
  max_age: number | null;
  school_levels: string[];
  variants: VideoVariant[];
}
